### ISSUE TITLE
Cannot read properties of undefined (reading 'node_id')

### ISSUE THREAD

**Issue by louagej** [a11smiles/GitSync#13]
Hi,

I forked the repository because my organization doesn't allow external repositories in our actions.
But I'm getting the error node_id is undefined.

```log
TypeError: Cannot read properties of undefined (reading 'node_id')
    at GitSync.run (/home/runner/work/_actions/myorg/GitSync/main/gitsync.js:28:30)
    at Object.<anonymous> (/home/runner/work/_actions/myorg/GitSync/main/index.js:4:6)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by a11smiles** [comment]
@louagej it seems that the property is different based on how the workflow is executed. In some cases it's `node_id` and in other cases is `nodeId`. I've added a check for that variance.

I've published v1.2.3 (along with merging back into `main`). 

Let me know if you still have problems.

**Comment by louagej** [comment]
Dear,

I tried to run the workflow on the latest changes, but I still have the same problem:

below the log of the GitSync step:
```workflowlog
2024-02-02T07:09:04.4800347Z ##[group]Run 9altitudes/GitSync@main
2024-02-02T07:09:04.4800854Z with:
2024-02-02T07:09:04.4801132Z env:
2024-02-02T07:09:04.4801388Z   ado_token: 
2024-02-02T07:09:04.4802350Z   github_token: ***
2024-02-02T07:09:04.4802772Z   config_file: ./.github/workflows/sync_config.json
2024-02-02T07:09:04.4803268Z ##[endgroup]
2024-02-02T07:09:05.4397715Z JSON configuration file loaded.
2024-02-02T07:09:05.4407882Z Setting logLevel to debug...
2024-02-02T07:09:05.4458138Z {
2024-02-02T07:09:05.4459053Z   log_level: 'debug',
2024-02-02T07:09:05.4459872Z   inputs: null,
2024-02-02T07:09:05.4460277Z   organization: {
2024-02-02T07:09:05.4461218Z     avatar_url: 'https://avatars.githubusercontent.com/u/141144569?v=4',
2024-02-02T07:09:05.4461952Z     description: '',
2024-02-02T07:09:05.4462559Z     events_url: 'https://api.github.com/orgs/9altitudes/events',
2024-02-02T07:09:05.4463383Z     hooks_url: 'https://api.github.com/orgs/9altitudes/hooks',
2024-02-02T07:09:05.4464413Z     id: 141144569,
2024-02-02T07:09:05.4465127Z     issues_url: 'https://api.github.com/orgs/9altitudes/issues',
2024-02-02T07:09:05.4465783Z     login: '9altitudes',
2024-02-02T07:09:05.4466467Z     members_url: 'https://api.github.com/orgs/9altitudes/members{/member}',
2024-02-02T07:09:05.4467195Z     node_id: 'O_kgDOCGmx-Q',
2024-02-02T07:09:05.4467988Z     public_members_url: 'https://api.github.com/orgs/9altitudes/public_members{/member}',
2024-02-02T07:09:05.4468957Z     repos_url: 'https://api.github.com/orgs/9altitudes/repos',
2024-02-02T07:09:05.4469687Z     url: 'https://api.github.com/orgs/9altitudes'
2024-02-02T07:09:05.4470189Z   },
2024-02-02T07:09:05.4470521Z   ref: 'refs/heads/main',
2024-02-02T07:09:05.4470904Z   repository: {
2024-02-02T07:09:05.4471249Z     allow_forking: false,
2024-02-02T07:09:05.4472140Z     archive_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/{archive_format}{/ref}',
2024-02-02T07:09:05.4472984Z     archived: false,
2024-02-02T07:09:05.4473822Z     assignees_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/assignees{/user}',
2024-02-02T07:09:05.4475073Z     blobs_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/git/blobs{/sha}',
2024-02-02T07:09:05.4476317Z     branches_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/branches{/branch}',
2024-02-02T07:09:05.4477394Z     clone_url: 'https://github.com/9altitudes/GTM-BC-9AFinanceBE.git',
2024-02-02T07:09:05.4478623Z     collaborators_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/collaborators{/collaborator}',
2024-02-02T07:09:05.4479996Z     comments_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/comments{/number}',
2024-02-02T07:09:05.4481247Z     commits_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/commits{/sha}',
2024-02-02T07:09:05.4482519Z     compare_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/compare/{base}...{head}',
2024-02-02T07:09:05.4483839Z     contents_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/contents/{+path}',
2024-02-02T07:09:05.4485111Z     contributors_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/contributors',
2024-02-02T07:09:05.4485996Z     created_at: '2024-01-16T09:30:29Z',
2024-02-02T07:09:05.4486466Z     custom_properties: {},
2024-02-02T07:09:05.4486900Z     default_branch: 'main',
2024-02-02T07:09:05.4487752Z     deployments_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/deployments',
2024-02-02T07:09:05.4488963Z     description: '9A Belgium Business Central Appsource for financial Belgium businesses ',
2024-02-02T07:09:05.4489725Z     disabled: false,
2024-02-02T07:09:05.4490488Z     downloads_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/downloads',
2024-02-02T07:09:05.4491624Z     events_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/events',
2024-02-02T07:09:05.4492346Z     fork: false,
2024-02-02T07:09:05.4492679Z     forks: 0,
2024-02-02T07:09:05.4492981Z     forks_count: 0,
2024-02-02T07:09:05.4494123Z     forks_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/forks',
2024-02-02T07:09:05.4494972Z     full_name: '9altitudes/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4495943Z     git_commits_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/git/commits{/sha}',
2024-02-02T07:09:05.4497198Z     git_refs_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/git/refs{/sha}',
2024-02-02T07:09:05.4498654Z     git_tags_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/git/tags{/sha}',
2024-02-02T07:09:05.4499693Z     git_url: 'git://github.com/9altitudes/GTM-BC-9AFinanceBE.git',
2024-02-02T07:09:05.4500313Z     has_discussions: false,
2024-02-02T07:09:05.4500704Z     has_downloads: true,
2024-02-02T07:09:05.4501084Z     has_issues: true,
2024-02-02T07:09:05.4501443Z     has_pages: true,
2024-02-02T07:09:05.4501788Z     has_projects: true,
2024-02-02T07:09:05.4502415Z     has_wiki: true,
2024-02-02T07:09:05.4502761Z     homepage: null,
2024-02-02T07:09:05.4503504Z     hooks_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/hooks',
2024-02-02T07:09:05.4504447Z     html_url: 'https://github.com/9altitudes/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4505044Z     id: 743926448,
2024-02-02T07:09:05.4505387Z     is_template: false,
2024-02-02T07:09:05.4506322Z     issue_comment_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/issues/comments{/number}',
2024-02-02T07:09:05.4508799Z     issue_events_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/issues/events{/number}',
2024-02-02T07:09:05.4510295Z     issues_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/issues{/number}',
2024-02-02T07:09:05.4511698Z     keys_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/keys{/key_id}',
2024-02-02T07:09:05.4512980Z     labels_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/labels{/name}',
2024-02-02T07:09:05.4513764Z     language: 'AL',
2024-02-02T07:09:05.4514473Z     languages_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/languages',
2024-02-02T07:09:05.4515206Z     license: null,
2024-02-02T07:09:05.4515881Z     merges_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/merges',
2024-02-02T07:09:05.4517029Z     milestones_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/milestones{/number}',
2024-02-02T07:09:05.4517802Z     mirror_url: null,
2024-02-02T07:09:05.4518212Z     name: 'GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4518665Z     node_id: 'R_kgDOLFdqsA',
2024-02-02T07:09:05.4519687Z     notifications_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/notifications{?since,all,participating}',
2024-02-02T07:09:05.4520605Z     open_issues: 0,
2024-02-02T07:09:05.4520939Z     open_issues_count: 0,
2024-02-02T07:09:05.4521287Z     owner: {
2024-02-02T07:09:05.4521879Z       avatar_url: 'https://avatars.githubusercontent.com/u/141144569?v=4',
2024-02-02T07:09:05.4522795Z       events_url: 'https://api.github.com/users/9altitudes/events{/privacy}',
2024-02-02T07:09:05.4523692Z       followers_url: 'https://api.github.com/users/9altitudes/followers',
2024-02-02T07:09:05.4524635Z       following_url: 'https://api.github.com/users/9altitudes/following{/other_user}',
2024-02-02T07:09:05.4525580Z       gists_url: 'https://api.github.com/users/9altitudes/gists{/gist_id}',
2024-02-02T07:09:05.4526217Z       gravatar_id: '',
2024-02-02T07:09:05.4526689Z       html_url: 'https://github.com/9altitudes',
2024-02-02T07:09:05.4527164Z       id: 141144569,
2024-02-02T07:09:05.4527542Z       login: '9altitudes',
2024-02-02T07:09:05.4527950Z       node_id: 'O_kgDOCGmx-Q',
2024-02-02T07:09:05.4528600Z       organizations_url: 'https://api.github.com/users/9altitudes/orgs',
2024-02-02T07:09:05.4529539Z       received_events_url: 'https://api.github.com/users/9altitudes/received_events',
2024-02-02T07:09:05.4530420Z       repos_url: 'https://api.github.com/users/9altitudes/repos',
2024-02-02T07:09:05.4530977Z       site_admin: false,
2024-02-02T07:09:05.4532007Z       starred_url: 'https://api.github.com/users/9altitudes/starred{/owner}{/repo}',
2024-02-02T07:09:05.4532998Z       subscriptions_url: 'https://api.github.com/users/9altitudes/subscriptions',
2024-02-02T07:09:05.4533706Z       type: 'Organization',
2024-02-02T07:09:05.4534216Z       url: 'https://api.github.com/users/9altitudes'
2024-02-02T07:09:05.4534693Z     },
2024-02-02T07:09:05.4534974Z     private: true,
2024-02-02T07:09:05.4535690Z     pulls_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/pulls{/number}',
2024-02-02T07:09:05.4536500Z     pushed_at: '2024-01-29T19:35:36Z',
2024-02-02T07:09:05.4599337Z     releases_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/releases{/id}',
2024-02-02T07:09:05.4600339Z     size: 166,
2024-02-02T07:09:05.4601004Z     ssh_url: 'git@github.com:9altitudes/GTM-BC-9AFinanceBE.git',
2024-02-02T07:09:05.4601593Z     stargazers_count: 0,
2024-02-02T07:09:05.4602777Z     stargazers_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/stargazers',
2024-02-02T07:09:05.4603961Z     statuses_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/statuses/{sha}',
2024-02-02T07:09:05.4605110Z     subscribers_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/subscribers',
2024-02-02T07:09:05.4606291Z     subscription_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/subscription',
2024-02-02T07:09:05.4607265Z     svn_url: 'https://github.com/9altitudes/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4608266Z     tags_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/tags',
2024-02-02T07:09:05.4610269Z     teams_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/teams',
2024-02-02T07:09:05.4611036Z     topics: [],
2024-02-02T07:09:05.4611865Z     trees_url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE/git/trees{/sha}',
2024-02-02T07:09:05.4612962Z     updated_at: '2024-01-16T11:19:30Z',
2024-02-02T07:09:05.4613673Z     url: 'https://api.github.com/repos/9altitudes/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4614333Z     visibility: 'private',
2024-02-02T07:09:05.4614701Z     watchers: 0,
2024-02-02T07:09:05.4615021Z     watchers_count: 0,
2024-02-02T07:09:05.4615383Z     web_commit_signoff_required: false
2024-02-02T07:09:05.4615793Z   },
2024-02-02T07:09:05.4616056Z   sender: {
2024-02-02T07:09:05.4616630Z     avatar_url: 'https://avatars.githubusercontent.com/u/7229592?v=4',
2024-02-02T07:09:05.4617734Z     events_url: 'https://api.github.com/users/louagej/events{/privacy}',
2024-02-02T07:09:05.4618632Z     followers_url: 'https://api.github.com/users/louagej/followers',
2024-02-02T07:09:05.4619538Z     following_url: 'https://api.github.com/users/louagej/following{/other_user}',
2024-02-02T07:09:05.4620441Z     gists_url: 'https://api.github.com/users/louagej/gists{/gist_id}',
2024-02-02T07:09:05.4621201Z     gravatar_id: '',
2024-02-02T07:09:05.4621677Z     html_url: 'https://github.com/louagej',
2024-02-02T07:09:05.4622173Z     id: 7229592,
2024-02-02T07:09:05.4622557Z     login: 'louagej',
2024-02-02T07:09:05.4622991Z     node_id: 'MDQ6VXNlcjcyMjk1OTI=',
2024-02-02T07:09:05.4623707Z     organizations_url: 'https://api.github.com/users/louagej/orgs',
2024-02-02T07:09:05.4624658Z     received_events_url: 'https://api.github.com/users/louagej/received_events',
2024-02-02T07:09:05.4625552Z     repos_url: 'https://api.github.com/users/louagej/repos',
2024-02-02T07:09:05.4626119Z     site_admin: false,
2024-02-02T07:09:05.4626813Z     starred_url: 'https://api.github.com/users/louagej/starred{/owner}{/repo}',
2024-02-02T07:09:05.4627909Z     subscriptions_url: 'https://api.github.com/users/louagej/subscriptions',
2024-02-02T07:09:05.4628577Z     type: 'User',
2024-02-02T07:09:05.4629011Z     url: 'https://api.github.com/users/louagej'
2024-02-02T07:09:05.4629472Z   },
2024-02-02T07:09:05.4630386Z   workflow: '.github/workflows/ghsync.yml',
2024-02-02T07:09:05.4630964Z   GRADLE_HOME: '/usr/share/gradle-8.5',
2024-02-02T07:09:05.4631743Z   LEIN_JAR: '/usr/local/lib/lein/self-installs/leiningen-2.11.0-standalone.jar',
2024-02-02T07:09:05.4632839Z   ImageVersion: '20240126.1.0',
2024-02-02T07:09:05.4633266Z   USER: 'runner',
2024-02-02T07:09:05.4633748Z   GOROOT_1_20_X64: '/opt/hostedtoolcache/go/1.20.13/x64',
2024-02-02T07:09:05.4634404Z   GECKOWEBDRIVER: '/usr/local/share/gecko_driver',
2024-02-02T07:09:05.4634933Z   STATS_NM: 'true',
2024-02-02T07:09:05.4635359Z   GHCUP_INSTALL_BASE_PREFIX: '/usr/local',
2024-02-02T07:09:05.4636428Z   STATS_EXTP: 'https://provjobdsettingscdn.blob.core.windows.net/settings/provjobdsettings-0.5.154/provjobd.data',
2024-02-02T07:09:05.4637391Z   SGX_AESM_ADDR: '1',
2024-02-02T07:09:05.4637768Z   LANG: 'C.UTF-8',
2024-02-02T07:09:05.4638254Z   INVOCATION_ID: '20c5dd6ff61b4e2c9405857c75c290ad',
2024-02-02T07:09:05.4638802Z   PIPX_HOME: '/opt/pipx',
2024-02-02T07:09:05.4639292Z   ANDROID_SDK_ROOT: '/usr/local/lib/android/sdk',
2024-02-02T07:09:05.4640048Z   STATS_V3PS: 'true',
2024-02-02T07:09:05.4640513Z   JAVA_HOME: '/usr/lib/jvm/temurin-11-jdk-amd64',
2024-02-02T07:09:05.4641284Z   ANDROID_NDK_LATEST_HOME: '/usr/local/lib/android/sdk/ndk/26.1.10909125',
2024-02-02T07:09:05.4641984Z   XDG_CONFIG_HOME: '/home/runner/.config',
2024-02-02T07:09:05.4642477Z   STATS_TIS: 'mining',
2024-02-02T07:09:05.4642868Z   NVM_DIR: '/home/runner/.nvm',
2024-02-02T07:09:05.4643390Z   HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650',
2024-02-02T07:09:05.4643926Z   CONDA: '/usr/share/miniconda',
2024-02-02T07:09:05.4644438Z   RUNNER_TOOL_CACHE: '/opt/hostedtoolcache',
2024-02-02T07:09:05.4644948Z   JOURNAL_STREAM: '8:16998',
2024-02-02T07:09:05.4645380Z   ACCEPT_EULA: 'Y',
2024-02-02T07:09:05.4645769Z   ANT_HOME: '/usr/share/ant',
2024-02-02T07:09:05.4646249Z   DEPLOYMENT_BASEPATH: '/opt/runner',
2024-02-02T07:09:05.4646890Z   POWERSHELL_DISTRIBUTION_CHANNEL: 'GitHub-Actions-ubuntu22',
2024-02-02T07:09:05.4648317Z   RUNNER_USER: 'runner',
2024-02-02T07:09:05.4648878Z   GOROOT_1_21_X64: '/opt/hostedtoolcache/go/1.21.6/x64',
2024-02-02T07:09:05.4649418Z   STATS_RDCL: 'true',
2024-02-02T07:09:05.4651373Z   PATH: '/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
2024-02-02T07:09:05.4653183Z   STATS_EXT: 'true',
2024-02-02T07:09:05.4653589Z   PIPX_BIN_DIR: '/opt/pipx_bin',
2024-02-02T07:09:05.4654049Z   SYSTEMD_EXEC_PID: '573',
2024-02-02T07:09:05.4654536Z   AGENT_TOOLSDIRECTORY: '/opt/hostedtoolcache',
2024-02-02T07:09:05.4655057Z   STATS_UE: 'true',
2024-02-02T07:09:05.4655418Z   STATS_VMD: 'true',
2024-02-02T07:09:05.4655977Z   RUNNER_TRACKING_ID: 'github_207738c9-2c72-4443-ae19-3663b0a8d625',
2024-02-02T07:09:05.4656653Z   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1',
2024-02-02T07:09:05.4657481Z   JAVA_HOME_17_X64: '/usr/lib/jvm/temurin-17-jdk-amd64',
2024-02-02T07:09:05.4658275Z   JAVA_HOME_8_X64: '/usr/lib/jvm/temurin-8-jdk-amd64',
2024-02-02T07:09:05.4658884Z   ANDROID_HOME: '/usr/local/lib/android/sdk',
2024-02-02T07:09:05.4659589Z   ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE: '/opt/actionarchivecache',
2024-02-02T07:09:05.4660357Z   SELENIUM_JAR_PATH: '/usr/share/java/selenium-server.jar',
2024-02-02T07:09:05.4660945Z   GITHUB_ACTIONS: 'true',
2024-02-02T07:09:05.4661464Z   JAVA_HOME_21_X64: '/usr/lib/jvm/temurin-21-jdk-amd64',
2024-02-02T07:09:05.4662197Z   ANDROID_NDK_HOME: '/usr/local/lib/android/sdk/ndk/25.2.9519653',
2024-02-02T07:09:05.4662885Z   EDGEWEBDRIVER: '/usr/local/share/edge_driver',
2024-02-02T07:09:05.4663443Z   DEBIAN_FRONTEND: 'noninteractive',
2024-02-02T07:09:05.4664031Z   GOROOT_1_19_X64: '/opt/hostedtoolcache/go/1.19.13/x64',
2024-02-02T07:09:05.4664626Z   STATS_TRP: 'true',
2024-02-02T07:09:05.4665028Z   XDG_RUNTIME_DIR: '/run/user/1001',
2024-02-02T07:09:05.4665622Z   JAVA_HOME_11_X64: '/usr/lib/jvm/temurin-11-jdk-amd64',
2024-02-02T07:09:05.4666239Z   RUNNER_PERFLOG: '/home/runner/perflog',
2024-02-02T07:09:05.4666724Z   STATS_BLT: 'true',
2024-02-02T07:09:05.4667541Z   CHROMEWEBDRIVER: '/usr/local/share/chromedriver-linux64',
2024-02-02T07:09:05.4668232Z   VCPKG_INSTALLATION_ROOT: '/usr/local/share/vcpkg',
2024-02-02T07:09:05.4668797Z   HOMEBREW_NO_AUTO_UPDATE: '1',
2024-02-02T07:09:05.4669423Z   ANDROID_NDK_ROOT: '/usr/local/lib/android/sdk/ndk/25.2.9519653',
2024-02-02T07:09:05.4670073Z   BOOTSTRAP_HASKELL_NONINTERACTIVE: '1',
2024-02-02T07:09:05.4670565Z   HOME: '/home/runner',
2024-02-02T07:09:05.4670937Z   CI: 'true',
2024-02-02T07:09:05.4671421Z   ANDROID_NDK: '/usr/local/lib/android/sdk/ndk/25.2.9519653',
2024-02-02T07:09:05.4672081Z   PERFLOG_LOCATION_SETTING: 'RUNNER_PERFLOG',
2024-02-02T07:09:05.4672591Z   ImageOS: 'ubuntu22',
2024-02-02T07:09:05.4673006Z   DOTNET_MULTILEVEL_LOOKUP: '0',
2024-02-02T07:09:05.4673466Z   LEIN_HOME: '/usr/local/lib/lein',
2024-02-02T07:09:05.4673974Z   SWIFT_PATH: '/usr/share/swift/usr/bin',
2024-02-02T07:09:05.4674732Z   CHROME_BIN: '/usr/bin/google-chrome',
2024-02-02T07:09:05.4675304Z   AZURE_EXTENSION_DIR: '/opt/az/azcliextensions',
2024-02-02T07:09:05.4675834Z   DOTNET_NOLOGO: '1',
2024-02-02T07:09:05.4676208Z   ado_token: '',
2024-02-02T07:09:05.4677466Z   github_token: '***',
2024-02-02T07:09:05.4678028Z   config_file: './.github/workflows/sync_config.json',
2024-02-02T07:09:05.4678557Z   INPUT_ADO: '',
2024-02-02T07:09:05.4678912Z   INPUT_GITHUB: '',
2024-02-02T07:09:05.4679282Z   GITHUB_JOB: 'alert',
2024-02-02T07:09:05.4679687Z   GITHUB_REF: 'refs/heads/main',
2024-02-02T07:09:05.4680266Z   GITHUB_SHA: '0e6fcd7a379360556ff889fa24cc84aea737e5fe',
2024-02-02T07:09:05.4680962Z   GITHUB_REPOSITORY: '9altitudes/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4681559Z   GITHUB_REPOSITORY_OWNER: '9altitudes',
2024-02-02T07:09:05.4682084Z   GITHUB_REPOSITORY_OWNER_ID: '141144569',
2024-02-02T07:09:05.4682591Z   GITHUB_RUN_ID: '7752600155',
2024-02-02T07:09:05.4683025Z   GITHUB_RUN_NUMBER: '431',
2024-02-02T07:09:05.4683471Z   GITHUB_RETENTION_DAYS: '90',
2024-02-02T07:09:05.4683898Z   GITHUB_RUN_ATTEMPT: '1',
2024-02-02T07:09:05.4684348Z   GITHUB_REPOSITORY_ID: '743926448',
2024-02-02T07:09:05.4684823Z   GITHUB_ACTOR_ID: '7229592',
2024-02-02T07:09:05.4685252Z   GITHUB_ACTOR: 'louagej',
2024-02-02T07:09:05.4685685Z   GITHUB_TRIGGERING_ACTOR: 'louagej',
2024-02-02T07:09:05.4686222Z   GITHUB_WORKFLOW: 'Sync with Azure DevOps',
2024-02-02T07:09:05.4686729Z   GITHUB_HEAD_REF: '',
2024-02-02T07:09:05.4687101Z   GITHUB_BASE_REF: '',
2024-02-02T07:09:05.4687541Z   GITHUB_EVENT_NAME: 'workflow_dispatch',
2024-02-02T07:09:05.4688096Z   GITHUB_SERVER_URL: 'https://github.com',
2024-02-02T07:09:05.4688670Z   GITHUB_API_URL: 'https://api.github.com',
2024-02-02T07:09:05.4689307Z   GITHUB_GRAPHQL_URL: 'https://api.github.com/graphql',
2024-02-02T07:09:05.4689884Z   GITHUB_REF_NAME: 'main',
2024-02-02T07:09:05.4690313Z   GITHUB_REF_PROTECTED: 'true',
2024-02-02T07:09:05.4690769Z   GITHUB_REF_TYPE: 'branch',
2024-02-02T07:09:05.4691601Z   GITHUB_WORKFLOW_REF: '9altitudes/GTM-BC-9AFinanceBE/.github/workflows/ghsync.yml@refs/heads/main',
2024-02-02T07:09:05.4692647Z   GITHUB_WORKFLOW_SHA: '0e6fcd7a379360556ff889fa24cc84aea737e5fe',
2024-02-02T07:09:05.4693542Z   GITHUB_WORKSPACE: '/home/runner/work/GTM-BC-9AFinanceBE/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4694281Z   GITHUB_ACTION: '__9altitudes_GitSync',
2024-02-02T07:09:05.4694990Z   GITHUB_EVENT_PATH: '/home/runner/work/_temp/_github_workflow/event.json',
2024-02-02T07:09:05.4695750Z   GITHUB_ACTION_REPOSITORY: '9altitudes/GitSync',
2024-02-02T07:09:05.4696440Z   GITHUB_ACTION_REF: 'main',
2024-02-02T07:09:05.4697666Z   GITHUB_PATH: '/home/runner/work/_temp/_runner_file_commands/add_path_e765e597-c4cf-4d6e-8215-511275797c5c',
2024-02-02T07:09:05.4698976Z   GITHUB_ENV: '/home/runner/work/_temp/_runner_file_commands/set_env_e765e597-c4cf-4d6e-8215-511275797c5c',
2024-02-02T07:09:05.4700329Z   GITHUB_STEP_SUMMARY: '/home/runner/work/_temp/_runner_file_commands/step_summary_e765e597-c4cf-4d6e-8215-511275797c5c',
2024-02-02T07:09:05.4701704Z   GITHUB_STATE: '/home/runner/work/_temp/_runner_file_commands/save_state_e765e597-c4cf-4d6e-8215-511275797c5c',
2024-02-02T07:09:05.4703295Z   GITHUB_OUTPUT: '/home/runner/work/_temp/_runner_file_commands/set_output_e765e597-c4cf-4d6e-8215-511275797c5c',
2024-02-02T07:09:05.4704146Z   RUNNER_OS: 'Linux',
2024-02-02T07:09:05.4704518Z   RUNNER_ARCH: 'X64',
2024-02-02T07:09:05.4704932Z   RUNNER_NAME: 'GitHub Actions 267',
2024-02-02T07:09:05.4705447Z   RUNNER_ENVIRONMENT: 'github-hosted',
2024-02-02T07:09:05.4706111Z   RUNNER_TEMP: '/home/runner/work/_temp',
2024-02-02T07:09:05.4706791Z   RUNNER_WORKSPACE: '/home/runner/work/GTM-BC-9AFinanceBE',
2024-02-02T07:09:05.4708228Z   ACTIONS_RUNTIME_URL: 'https://pipelinesghubeus13.actions.githubusercontent.com/pSo7Al5JDNxGOE0Wvg0mrPBQ65gxv2jP3FookafJuz25edfQgJ/',
2024-02-02T07:09:05.4768074Z   ACTIONS_RUNTIME_TOKEN: '***',
2024-02-02T07:09:05.4769322Z   ACTIONS_CACHE_URL: 'https://acghubeus2.actions.githubusercontent.com/pSo7Al5JDNxGOE0Wvg0mrPBQ65gxv2jP3FookafJuz25edfQgJ/',
2024-02-02T07:09:05.4771205Z   ACTIONS_RESULTS_URL: 'https://results-receiver.actions.githubusercontent.com/',
2024-02-02T07:09:05.4771927Z   ado: {
2024-02-02T07:09:05.4772302Z     organization: '9altitudes-GTM',
2024-02-02T07:09:05.4772858Z     project: '9A - Business Central Solutions',
2024-02-02T07:09:05.4773362Z     wit: 'User Story',
2024-02-02T07:09:05.4773699Z     states: {
2024-02-02T07:09:05.4774029Z       new: 'New',
2024-02-02T07:09:05.4774387Z       closed: 'Closed',
2024-02-02T07:09:05.4774760Z       reopened: 'New',
2024-02-02T07:09:05.4775148Z       deleted: 'Removed',
2024-02-02T07:09:05.4775543Z       active: 'Active'
2024-02-02T07:09:05.4775850Z     },
2024-02-02T07:09:05.4776132Z     bypassRules: true,
2024-02-02T07:09:05.4776479Z     autoCreate: true,
2024-02-02T07:09:05.4776973Z     orgUrl: 'https://dev.azure.com/9altitudes-GTM'
2024-02-02T07:09:05.4778259Z   },
2024-02-02T07:09:05.4778574Z   github: {
2024-02-02T07:09:05.4779811Z     token: '***'
2024-02-02T07:09:05.4780190Z   }
2024-02-02T07:09:05.4780453Z }
2024-02-02T07:09:05.4781102Z TypeError: Cannot read properties of undefined (reading 'node_id')
2024-02-02T07:09:05.4782184Z     at GitSync.run (/home/runner/work/_actions/9altitudes/GitSync/main/gitsync.js:28:31)
2024-02-02T07:09:05.4783264Z     at Object.<anonymous> (/home/runner/work/_actions/9altitudes/GitSync/main/index.js:4:6)
2024-02-02T07:09:05.4784262Z     at Module._compile (node:internal/modules/cjs/loader:1198:14)
2024-02-02T07:09:05.4785054Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2024-02-02T07:09:05.4785822Z     at Module.load (node:internal/modules/cjs/loader:1076:32)
2024-02-02T07:09:05.4786537Z     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2024-02-02T07:09:05.4787411Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2024-02-02T07:09:05.4788182Z     at node:internal/main/run_main_module:22:47
```

**Comment by a11smiles** [comment]
fixed with merged code.
